[tool.poetry]
name = "ayon-core"
version = "0.1.0"
description = ""
authors = ["Ondřej Samohel <ondrej.samohel@ynput.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9.1,<3.10"
aiohttp_json_rpc = "*" # TVPaint server
aiohttp-middlewares = "^2.0.0"
wsrpc_aiohttp = "^3.1.1" # websocket server
Click = "^8"
clique = "1.6.*"
jsonschema = "^4"
pyblish-base = "^1.8.11"
pynput = "^1.7.2" # Timers manager - TODO remove
speedcopy = "^2.1"
six = "^1.15"
qtawesome = "0.7.3"
openassetio-traitgen = "*" # for generating traits from yaml definitions
openassetio-mediacreation = "*" # for default media creation traits
ayon-openassetio-manager-plugin = { git = "https://github.com/ynput/ayon-openassetio-manager-plugin.git", branch = "main" }
deal = "^4.24.3"


[tool.poetry.dev-dependencies]
pytest = "^8.0"
pytest-print = "^1.0"
ayon-python-api = "^1.0"
arrow = "^1.3.0"
wemake-python-styleguide = "*"
isort="*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
