name: 📇 Code Linting

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number}}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.9" ]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies library
        run: |
          pip install ruff
        shell: bash
      - name: Annotate PR with Ruff
        uses: EnriqueSoria/annotate_pr_with_ruff@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
